# Generated by Django 5.0.1 on 2024-03-05 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidato',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
