# Generated by Django 5.0.1 on 2024-03-05 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0002_candidato_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidato',
            name='candidato',
            field=models.IntegerField(choices=[(1, 'Regular'), (2, 'Bueno'), (3, 'Muy Bueno')]),
        ),
    ]
